---

name: check_sharepoint_sync
version: 1.1.0

cron: 0,15,30,45 * * * *
sleep: 60

mail:
  server: mail.sidmar.be
  port: 25
  subject: A machine is not syncing sharepoint
  text: The sharepoint sync seems to be out of date on machine
  from: check_sharepoint_sync@arcelormittal.com

buddies:
  - name: svsim1hl
    to:
      - yves.vindevogel.external@arcelormittal.com
      - luc.vandeputte@arcelormittal.com
  - name: svkwa358
    to:
      - yves.vindevogel.external@arcelormittal.com
      - tom.nobels@arcelormittal.com
  - name: ws40968
    to:
      - yves.vindevogel.external@arcelormittal.com

sync_dir:
  root_var: AMPythonCommunity
  sub_dirs:
  - Jobs
  - Belgium
  - check_sharepoint_sync

sync_dir_en:
  - ArcelorMittal
  - AM Python - Documents
  - Jobs
  - Belgium
  - check_sharepoint_sync

skip_files:
  - README_FIRST.txt

sync_delta: 1200


